// Моковые данные напитков
export const staticDrinks = [
  {
    id: '1',
    name: 'Эспрессо',
    name_en: 'Espresso',
    description: 'Классический крепкий кофе, приготовленный под высоким давлением. Идеален для утреннего пробуждения.',
    image_url: 'https://www.marketresearchintellect.com/images/blogs/sipping-success-exploring-the-dynamics-of-the-espresso-coffee-market.webp',
    category: 'espresso',
    strength: 5,
    bitterness: 4,
    acidity: 3,
    sweetness: 1,
    caffeine_mg: 64,
    volume_ml: 30,
    brewing_method: 'эспрессо-машина',
    mood_tags: ['бодрость', 'концентрация'],
    time_of_day: ['утро', 'день'],
    ingredients: ['кофе молотый'],
    temperature: 'горячий',
    origin: 'Италия'
  },
  {
    id: '2',
    name: 'Капучино',
    name_en: 'Cappuccino',
    description: 'Идеальный баланс эспрессо, молока и молочной пены. Нежный и насыщенный вкус.',
    image_url: 'https://mircoffee.ru/ckfinder/userfiles/images/1348611114_02-kapuchino.jpg',
    category: 'milk_based',
    strength: 3,
    bitterness: 2,
    acidity: 2,
    sweetness: 3,
    caffeine_mg: 64,
    volume_ml: 180,
    brewing_method: 'эспрессо-машина',
    mood_tags: ['расслабление', 'уют'],
    time_of_day: ['утро', 'день'],
    ingredients: ['эспрессо', 'молоко', 'молочная пена'],
    temperature: 'горячий',
    origin: 'Италия'
  },
  {
    id: '3',
    name: 'Латте',
    name_en: 'Latte',
    description: 'Мягкий кофейный напиток с большим количеством молока. Идеален для расслабления.',
    image_url: 'https://coffee61.ru/wa-data/public/photos/68/03/368/368.970.jpg',
    category: 'milk_based',
    strength: 2,
    bitterness: 1,
    acidity: 1,
    sweetness: 4,
    caffeine_mg: 64,
    volume_ml: 240,
    brewing_method: 'эспрессо-машина',
    mood_tags: ['расслабление', 'уют', 'романтика'],
    time_of_day: ['день', 'вечер'],
    ingredients: ['эспрессо', 'молоко'],
    temperature: 'горячий',
    origin: 'США'
  },
  {
    id: '4',
    name: 'Американо',
    name_en: 'Americano',
    description: 'Эспрессо с добавлением горячей воды. Менее концентрированный, но такой же ароматный.',
    image_url: 'https://coffe-spb.ru/img/cms/americano.jpg',
    category: 'espresso',
    strength: 3,
    bitterness: 3,
    acidity: 2,
    sweetness: 1,
    caffeine_mg: 64,
    volume_ml: 120,
    brewing_method: 'эспрессо-машина',
    mood_tags: ['бодрость', 'концентрация'],
    time_of_day: ['утро', 'день'],
    ingredients: ['эспрессо', 'вода'],
    temperature: 'горячий',
    origin: 'США'
  },
  {
    id: '5',
    name: 'Раф кофе',
    name_en: 'Raf Coffee',
    description: 'Российский кофейный напиток на основе эспрессо, сливок и ванильного сахара.',
    image_url: 'https://www.coffeejeromaya.ru/_bl/0/78696242.jpg',
    category: 'specialty',
    strength: 2,
    bitterness: 1,
    acidity: 1,
    sweetness: 5,
    caffeine_mg: 64,
    volume_ml: 180,
    brewing_method: 'эспрессо-машина',
    mood_tags: ['уют', 'расслабление'],
    time_of_day: ['день', 'вечер'],
    ingredients: ['эспрессо', 'сливки', 'ванильный сахар'],
    temperature: 'горячий',
    origin: 'Россия'
  },
  {
    id: '6',
    name: 'Холодный американо',
    name_en: 'Iced Americano',
    description: 'Освежающий холодный кофе с насыщенным вкусом. Идеален в жаркую погоду.',
    image_url: 'https://i.pinimg.com/736x/ee/5c/fc/ee5cfc0f10bfc454dda4c943b749866b.jpg',
    category: 'cold_brew',
    strength: 3,
    bitterness: 3,
    acidity: 2,
    sweetness: 1,
    caffeine_mg: 64,
    volume_ml: 300,
    brewing_method: 'эспрессо-машина',
    mood_tags: ['бодрость', 'творчество'],
    time_of_day: ['день', 'вечер'],
    ingredients: ['эспрессо', 'вода', 'лёд'],
    temperature: 'горячий',
    origin: 'США'
  },
  {
    id: '7',
    name: 'Фильтр кофе',
    name_en: 'Filter Coffee',
    description: 'Классический фильтр-кофе с чистым и ярким вкусом. Подчеркивает ноты кофейных зерен.',
    image_url: 'https://ir.ozone.ru/s3/multimedia-1-2/w500/7027888070.jpg',
    category: 'filter',
    strength: 3,
    bitterness: 2,
    acidity: 4,
    sweetness: 2,
    caffeine_mg: 95,
    volume_ml: 200,
    brewing_method: 'pour over',
    mood_tags: ['творчество', 'концентрация'],
    time_of_day: ['утро', 'день'],
    ingredients: ['кофе молотый'],
    temperature: 'горячий',
    origin: 'Эфиопия'
  },
  {
    id: '8',
    name: 'Флэт Уайт',
    name_en: 'Flat White',
    description: 'Австралийский кофейный напиток с тонким слоем микропены. Интенсивный кофейный вкус.',
    image_url: 'https://i-coffee.me/wp-content/uploads/2022/03/26a016c7b14865965c65b0f914bee618-680x500-1.jpeg',
    category: 'milk_based',
    strength: 4,
    bitterness: 3,
    acidity: 2,
    sweetness: 2,
    caffeine_mg: 130,
    volume_ml: 160,
    brewing_method: 'эспрессо-машина',
    mood_tags: ['концентрация', 'бодрость'],
    time_of_day: ['утро', 'день'],
    ingredients: ['эспрессо', 'молоко'],
    temperature: 'горячий',
    origin: 'Австралия'
  },
  {
    id: '9', // Уникальный ID (просто следующий номер)
    name: 'Мокка',
    name_en: 'Mocha',
    description: 'Шоколадный кофе с молоком. Идеальное сочетание кофе и шоколада.',
    image_url: 'https://mircoffee.ru/ckfinder/userfiles/images/6__3.jpg',
    category: 'specialty',
    strength: 3,
    bitterness: 2,
    acidity: 2,
    sweetness: 4,
    caffeine_mg: 95,
    volume_ml: 240,
    brewing_method: 'эспрессо-машина',
    mood_tags: ['уют', 'романтика', 'расслабление'],
    time_of_day: ['день', 'вечер'],
    ingredients: ['эспрессо', 'молоко', 'шоколадный сироп'],
    temperature: 'горячий',
    origin: 'США'
  },
];

// Локальное хранилище избранного
let favorites = JSON.parse(localStorage.getItem('coffeeFavorites')) || [];

export const saveFavorites = () => {
  localStorage.setItem('coffeeFavorites', JSON.stringify(favorites));
};

export const getFavorites = () => [...favorites];
export const setFavorites = (newFavorites) => {
  favorites = newFavorites;
  saveFavorites();
};